### PR TITLE
Frontend Refactor and Mock Data

### PR DESCRIPTION
**Pull request by jakehwll**
## Description

This pull-request introduces the following changes in order to make this repository slightly easier to consume.

* Removes the dependency on `jQuery` as everything it was doing was achievable in easy native javascript.
* Refactors..
  * Removes the function lookup for colors (use an indexed object).
  * Removes `function` definitions in favor of `const` flavour.
* Adds the capability to use a `.venv` alongside proper requirements in the `requirements.txt`.
* Adds a sample `.env` file.
* Adds a customisable port using said environment file.
* Adds a `README.md` to accurately describe how to get started easier ( placeholder? )
* Adds some mock data for the `puzzles.json` file with a `mock-puzzles.json`

### CODE REVIEW

**Comment by davidcoates** [comment]
Group colours are broken for me:

image

**Comment by davidcoates** [comment]
Puzzle selection drop down does not have any effect

**Comment by jakehwll** [comment]
> Group colours are broken for me:
> 
> ...

Good catch, I've gone ahead and resolved the lookup for these. Should really consider moving this codebase to typescript in order to catch issues like these 👍🏻

**Comment by davidcoates** [comment]
image

Game board not rendered on page load

**Comment by davidcoates** [comment]
LGTM :+1:

**Pull request merged**
